create table t_call_ratio
(
id    bigint not null auto_increment,
city_code    varchar(6)  comment '市分代码',
city_name    varchar(64)  comment '市分名称',
area_code    varchar(8)  comment '县分代码',
area_name    varchar(64)  comment '县分名称',
net_code    varchar(11)  comment '网点代码',
net_name    varchar(96)  comment '网点名称',
real_count    int(4)  comment '实际回访量',
stand_count    int(4)  comment '标准件',
call_intime    int(4)  comment '犹豫期内电话回访成功量',
call_ratio    varchar(7)  comment '犹豫期内电话回访成功率',
fail_door    int(4)  comment '不成功件-已上门回访-未成功面见投保人',
fail_letter    int(4)  comment '不成功件-信函已发-未回函',
fail_confirm    int(4)  comment '不成功件-身份核实问题',
fail_else    int(4)  comment '不成功件-其他',
fail_report    int(4)  comment '不成功件-因涉及投诉无法完成回访',
fail_complaint    int(4)  comment '不成功件-身体原因无法进行回访',
fail_sale    int(4)  comment '不成功件-销售误导未完成回访',
fail_ct    int(4)  comment '不成功件-退保未完成回访',
fail_fit    int(4)  comment '不成功件-客户不配合，无法完成身份核实',
fail_notdeal    int(4)  comment '不成功件-客户称未办理',
fail_cut    int(4)  comment '不成功件-客户挂断',
fail_noanswer    int(4)  comment '不成功件-无法接通',
fail_lenguage    int(4)  comment '不成功件-方言',
fail_link    int(4)  comment '不成功件-无法联系客户',
fail_err    int(4)  comment '不成功件-电话错误',
fail_nobody    int(4)  comment '不成功件-无人接听',
fail_count    int(4)  comment '不成功件合计',
issue_else    int(4)  comment '问题件-其他',
issue_tell    int(4)  comment '问题件-健康财务状况不如实告知',
issue_write    int(4)  comment '问题件-未抄写风险提示语',
issue_ct    int(4)  comment '问题件-意向退保',
issue_sign1    int(4)  comment '问题件-投保人代签名',
issue_sign2    int(4)  comment '问题件-被保人代签名',
issue_saving    int(4)  comment '问题件-条款解释不清-存款',
issue_profit    int(4)  comment '问题件-条款解释不清-产品收益',
issue_period    int(4)  comment '问题件-条款解释不清-犹豫期',
issue_duration    int(4)  comment '问题件-条款解释不清-保险期间',
issue_duty    int(4)  comment '问题件-条款解释不清-保险责任',
issue_intend    int(4)  comment '问题件-双录非本人意愿',
issue_record    int(4)  comment '问题件-未双录',
issue_delivery    int(4)  comment '问题件-保单未送达',
issue_count    int(4)  comment '问题件合计',
reject_count    int(4)  comment '拒访件合计',
ct_count    int(4)  comment '退保件合计',
order_count    int(4)  comment '预约件合计',
wait_count    int(4)  comment '待回访合计',
success_ratio    varchar(7)  comment '成功率',
attached_ratio    varchar(7)  comment '附件上传率',
record_ratio    varchar(7)  comment '录音上传率',
issue_percent    varchar(7)  comment '问题件占比',
s_date    date  comment '开始时候',
e_date    date  comment '结束时间',
operate_id           bigint,
operate_time         date,
primary key (id)
)
engine=innodb auto_increment=1 default charset=utf8mb4;